/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as LoginStaffRouteImport } from './routes/login.staff'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppLocationsRouteImport } from './routes/_app.locations'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppReportsNewRouteImport } from './routes/_app.reports.new'
import { Route as AppReportsIdRouteImport } from './routes/_app.reports.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LoginStaffRoute = LoginStaffRouteImport.update({
  id: '/login/staff',
  path: '/login/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsNewRoute = AppReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsIdRoute = AppReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/audit': typeof AppAuditRoute
  '/documents': typeof AppDocumentsRoute
  '/locations': typeof AppLocationsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/login/admin': typeof LoginAdminRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/': typeof LoginIndexRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/reports/new': typeof AppReportsNewRoute
}
export interface FileRoutesByTo {
  '/audit': typeof AppAuditRoute
  '/documents': typeof AppDocumentsRoute
  '/locations': typeof AppLocationsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/login/admin': typeof LoginAdminRoute
  '/login/staff': typeof LoginStaffRoute
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/reports/new': typeof AppReportsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/login/admin': typeof LoginAdminRoute
  '/login/staff': typeof LoginStaffRoute
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_app/reports/$id': typeof AppReportsIdRoute
  '/_app/reports/new': typeof AppReportsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/documents'
    | '/locations'
    | '/reports'
    | '/login/admin'
    | '/login/staff'
    | '/login/'
    | '/reports/$id'
    | '/reports/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/audit'
    | '/documents'
    | '/locations'
    | '/reports'
    | '/login/admin'
    | '/login/staff'
    | '/'
    | '/login'
    | '/reports/$id'
    | '/reports/new'
  id:
    | '__root__'
    | '/_app'
    | '/_app/audit'
    | '/_app/documents'
    | '/_app/locations'
    | '/_app/reports'
    | '/login/admin'
    | '/login/staff'
    | '/_app/'
    | '/login/'
    | '/_app/reports/$id'
    | '/_app/reports/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginAdminRoute: typeof LoginAdminRoute
  LoginStaffRoute: typeof LoginStaffRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/login/staff': {
      id: '/login/staff'
      path: '/login/staff'
      fullPath: '/login/staff'
      preLoaderRoute: typeof LoginStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/new': {
      id: '/_app/reports/new'
      path: '/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AppReportsNewRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/$id': {
      id: '/_app/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AppReportsIdRouteImport
      parentRoute: typeof AppReportsRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsIdRoute: typeof AppReportsIdRoute
  AppReportsNewRoute: typeof AppReportsNewRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsIdRoute: AppReportsIdRoute,
  AppReportsNewRoute: AppReportsNewRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginAdminRoute: LoginAdminRoute,
  LoginStaffRoute: LoginStaffRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
